apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: storelocator
  namespace: experimental
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: storelocator
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 50
    